Assignment 2 ljy
stargrep/2022-winter-bootcamp pull request #15
Opened 2022-02-10 01:45 UTC by ljymr

2022-02-10 01:45 UTC, ljymr commented
complete assignment

2022-02-12 13:52 UTC, stargrep commented
need to chat offline.

2022-02-12 14:24 UTC, stargrep requested changes

2022-02-12 14:24 UTC, stargrep commented on week03/assignment2 - lijunyan/assignment2 lijunyan.py
> +def selection_sort(arr: [[int]]) -> [[int]]:
use selection sort instead of bubble sort

2022-02-12 14:24 UTC, stargrep commented on week03/assignment2 - lijunyan/assignment2 lijunyan.py
> +    pass
unnecessary pass 

k v k v
for ....:
    di[k] = v

2022-02-12 14:24 UTC, stargrep commented on week03/assignment2 - lijunyan/assignment2 lijunyan.py
> +>>> concatenate([[1, 2], [3, 4]])
add some tests

2022-02-13 15:27 UTC, closed without merging