Assignment 2 Huang
stargrep/2022-winter-bootcamp pull request #16
Opened 2022-02-11 08:39 UTC by KittenLR

2022-02-12 14:32 UTC, stargrep requested changes

2022-02-12 14:32 UTC, stargrep commented on week03/07_Numpy.ipynb
> +  },
don't change this file.

2022-02-12 14:32 UTC, stargrep commented on week03/assignment2/assignment2 - Huang.py
> +def rotate(ar: [int], d: int) -> [int]:
can do in one line

2022-02-12 14:32 UTC, stargrep commented on week03/assignment2/assignment2 - Huang.py
> +    pass
I think di[k, v] would work.
remove 'pass'

2022-02-14 12:18 UTC, KittenLR commented on week03/07_Numpy.ipynb
> +  },
file reverted

2022-02-14 12:22 UTC, KittenLR commented on week03/assignment2/assignment2 - Huang.py
> +def rotate(ar: [int], d: int) -> [int]:
Done

2022-02-19 14:00 UTC, stargrep approved these changes

2022-02-19 14:01 UTC, merged