assignment1-haojin
stargrep/2022-winter-bootcamp pull request #8
Opened 2022-02-01 06:25 UTC by haojinliang

assignment 1 haojin

2022-02-05 14:14 UTC, stargrep requested changes

2022-02-05 18:19 UTC, haojinliang commented on week02/assignment/assignment1-Haojin.py
> +    if year > 0:
def is_leap_year(year: int) -> bool:
    return True if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0) else False

2022-02-05 18:19 UTC, haojinliang commented on week02/assignment/assignment1-Haojin.py
> +    if bool(a or b) != bool(a and b):
def xor(a: bool, b: bool) -> bool:
    return True if a != b else False

2022-02-05 18:22 UTC, haojinliang reviewed
resolved

2022-02-06 13:52 UTC, stargrep approved these changes

2022-02-06 13:52 UTC, stargrep commented on week02/assignment/assignment1-Haojin.py
> +    return True if a != b else False
minor: just return a != b

2022-02-06 13:52 UTC, merged